### PR TITLE
Minor tweaks and things: 

### PR DESCRIPTION
**Pull request by anothercookiecrumbles**
- Adds disclaimer in index.html (retrospective and methodology to come)
- Sends through the date from the server-side to get 'round inconsistent date/locale handling across the different browsers
- Improves logic and narrative for timediff calculations
- Tabs vs. spaces (Spaces FTW)

### CODE REVIEW

**Comment by jonahsmith** [comment]
This all looks good. Before I merge, can you add `pytz` to `requirements.txt`? We should try to keep that up to date.

(While you're at it, there's probably some extra cruft in there that could be removed, mostly related to Flask. As an aside, I wonder if we should separate the "analysis" and "playback" requirements--the scipy stuff is time consuming to install and unnecessary if you're just playing back data and not generating it.)

**Comment by anothercookiecrumbles** [comment]
Think that we should split the playback stuff into its own module. Is that effectively splitting out 0_streaming_server? 

Added pytz to requirements.txt (and removed flask and a bunch of other dependencies that don't seem to be used).

**Comment by jonahsmith** [comment]
And I think `protobuf` is a dependency of `gtfs-realtime-bindings`, would you mind adding that back? It would probably be okay, just want to make sure we don't end up with bizarre sub-dependency issues. Then I'll merge this branch.

Let's discuss splicing out different sections in #2 .

**Comment by anothercookiecrumbles** [comment]
That's done.

**Pull request merged**
